name: Trigger Azure Pipeline 

on:
  workflow_dispatch:

jobs:
  triggerAzurePipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Azure DevOps Pipeline on Develop Branch
        run: |
          AZURE_PIPELINE_URL="https://dev.azure.com/moboco/moboco_doc/_apis/build/builds?api-version=6.0"
          BODY='{"definition":{"id":8},"sourceBranch":"refs/heads/develop"}'
          curl -X POST "$AZURE_PIPELINE_URL" -H "Content-Type: application/json" -H "Authorization: Basic $(echo -n ":aaa" | base64)" -d "$BODY"
